//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuTools.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DuTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   웹사이트를 열 수 없어요!\r\n과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CannotOpenWebsite {
            get {
                return ResourceManager.GetString("CannotOpenWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   콘솔 스크립트를 읽을 수 없어요:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CannotReadConsoleScript {
            get {
                return ResourceManager.GetString("CannotReadConsoleScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스크립트 종료: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConsoleScriptExitWith {
            get {
                return ResourceManager.GetString("ConsoleScriptExitWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   콘솔 스크립트|*.duc;*.duconsole;*.cmd;*.ps1|모든 파일|*.*과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConsoleScriptFilter {
            get {
                return ResourceManager.GetString("ConsoleScriptFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DuBook과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DefaultBookName {
            get {
                return ResourceManager.GetString("DefaultBookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   합시다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DoIt {
            get {
                return ResourceManager.GetString("DoIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일이름: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileNameWith {
            get {
                return ResourceManager.GetString("FileNameWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap icon_cmd_Calculator {
            get {
                object obj = ResourceManager.GetObject("icon_cmd_Calculator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap icon_cmd_Converter1 {
            get {
                object obj = ResourceManager.GetObject("icon_cmd_Converter1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap icon_cmd_DuConsole {
            get {
                object obj = ResourceManager.GetObject("icon_cmd_DuConsole", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap icon_cmd_DuGetBlog {
            get {
                object obj = ResourceManager.GetObject("icon_cmd_DuGetBlog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   콘솔 런타임이 잘못됐어요: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidConsoleRuntime {
            get {
                return ResourceManager.GetString("InvalidConsoleRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알려주세여!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LetMeKnow {
            get {
                return ResourceManager.GetString("LetMeKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   책 이름을 써주세요! 파일 이름으로 사용해요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoBookName {
            get {
                return ResourceManager.GetString("NoBookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [콘솔 스크립트가 없어요]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoConsoleScript {
            get {
                return ResourceManager.GetString("NoConsoleScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   콘솔 스크립트가 없어요. 먼저 여세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoConsoleScriptOpenFirst {
            get {
                return ResourceManager.GetString("NoConsoleScriptOpenFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지원하지 않는 블로그 사이트예요!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoSupportBlogSite {
            get {
                return ResourceManager.GetString("NoSupportBlogSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL 주소가 없어요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoUrlAddress {
            get {
                return ResourceManager.GetString("NoUrlAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   열기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스크립트부터 열어주세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpenConsoleScriptPlease {
            get {
                return ResourceManager.GetString("OpenConsoleScriptPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DuConsole용 확장자를 등록할까요?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegisterExtensionsDuConsole {
            get {
                return ResourceManager.GetString("RegisterExtensionsDuConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그밖의 확장자를 등록할까요?\r\n아직 정해진건 없어요!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegisterExtensionsOthers {
            get {
                return ResourceManager.GetString("RegisterExtensionsOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   콘솔 스크립트를 고르세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectConsoleScript {
            get {
                return ResourceManager.GetString("SelectConsoleScript", resourceCulture);
            }
        }
    }
}
